//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public int doctorId { get; set; }
        public int PatientId { get; set; }
        public Nullable<System.DateTime> dateOfVisit { get; set; }
        public string complaint { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient2 Patient2 { get; set; }
    }
}
